url: https://smcprogramming.club
baseurl:

# Site settings
title: SMC Programming Club
email: smcprogramming@gmail.com
description: "A club for programmers at SMC to get together and work on awesome projects."

# Color settings (hex-codes without the leading hash-tag)
# color:
#   primary: fed136
#   secondary: fec503
#   secondary-dark: 333
color:
  primary: 3498db
  secondary: 2980b9
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Luis Chavez
  pic: luis
  position: President
  social:

- name: Justin Goldberg
  pic: justin
  position: Vice President
  social:

- name: Carlos Vega
  pic: placeholder
  position: Treasurer
  social:

- name: Kaomi Booker
  pic: kaomi
  position: Secretary
  social:

- name: Jesus Ramos
  pic: jesus
  position: Community Outreach
  social:

#- name: Luis Chavez
#  pic: luis
#  position: Event Coordinator
#  social:


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/groups/smccsande/
  - title: github
    url: https://github.com/smcprogrammingclub

# Postal address (add as many lines as necessary)
address:
  - line: NULL

# Build settings
markdown: kramdown
permalink: pretty
